// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI2g5boVoFcf0QD9Vov5bR5Qj18SVAvu4',
    appId: '1:269134980056:web:30eeb59d7fd0f6182848ad',
    messagingSenderId: '269134980056',
    projectId: 'flutter-notifications-8908b',
    authDomain: 'flutter-notifications-8908b.firebaseapp.com',
    storageBucket: 'flutter-notifications-8908b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ3bh03lRv_R8hYoGBTnC1b9j6fMQLM5U',
    appId: '1:269134980056:android:e5f273c80f98f2ac2848ad',
    messagingSenderId: '269134980056',
    projectId: 'flutter-notifications-8908b',
    storageBucket: 'flutter-notifications-8908b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXIoMWoxIZ7S_uyv7RPLmpXsGeFpqIoRY',
    appId: '1:269134980056:ios:b6b872e88fd928d22848ad',
    messagingSenderId: '269134980056',
    projectId: 'flutter-notifications-8908b',
    storageBucket: 'flutter-notifications-8908b.appspot.com',
    iosClientId: '269134980056-08mogkgnuejqjua8dhcp3eh6sa6oc4h7.apps.googleusercontent.com',
    iosBundleId: 'com.flutternotifications.flutterNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXIoMWoxIZ7S_uyv7RPLmpXsGeFpqIoRY',
    appId: '1:269134980056:ios:cbd121d49b5886852848ad',
    messagingSenderId: '269134980056',
    projectId: 'flutter-notifications-8908b',
    storageBucket: 'flutter-notifications-8908b.appspot.com',
    iosClientId: '269134980056-9qfs41l7fksqlnn6k1u1rs2a0g8fhg2j.apps.googleusercontent.com',
    iosBundleId: 'com.flutternotifications.flutterNotifications.RunnerTests',
  );
}
